//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserAppDatas = new HashSet<AspNetUserAppData>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.AspNetUserRoles1 = new HashSet<AspNetUserRole>();
            this.GST_MST_USER_SIGNATORY = new HashSet<GST_MST_USER_SIGNATORY>();
            this.GST_MST_ITEM = new HashSet<GST_MST_ITEM>();
            this.GST_MST_PRESENT_USER = new HashSet<GST_MST_PRESENT_USER>();
            this.GST_MST_PURCHASE_REGISTER = new HashSet<GST_MST_PURCHASE_REGISTER>();
            this.GST_MST_REPORT_PERMISSION = new HashSet<GST_MST_REPORT_PERMISSION>();
            this.GST_MST_SALE_REGISTER = new HashSet<GST_MST_SALE_REGISTER>();
            this.GST_MST_USER_BUSINESSTYPE = new HashSet<GST_MST_USER_BUSINESSTYPE>();
            this.GST_MST_USER_CURRENT_TURNOVER = new HashSet<GST_MST_USER_CURRENT_TURNOVER>();
            this.GST_MST_VENDOR = new HashSet<GST_MST_VENDOR>();
            this.GST_TRN_CRDR_NOTE = new HashSet<GST_TRN_CRDR_NOTE>();
            this.GST_TRN_CRDR_NOTE1 = new HashSet<GST_TRN_CRDR_NOTE>();
            this.GST_TRN_INVOICE = new HashSet<GST_TRN_INVOICE>();
            this.GST_TRN_INVOICE1 = new HashSet<GST_TRN_INVOICE>();
            this.GST_TRN_INVOICE2 = new HashSet<GST_TRN_INVOICE>();
            this.GST_TRN_ITC = new HashSet<GST_TRN_ITC>();
            this.GST_TRN_OFFLINE_INVOICE = new HashSet<GST_TRN_OFFLINE_INVOICE>();
            this.GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL = new HashSet<GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL>();
            this.GST_TRN_RETURN_STATUS = new HashSet<GST_TRN_RETURN_STATUS>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string GSTNNo { get; set; }
        public string ParentUserID { get; set; }
        public string OrganizationName { get; set; }
        public string Address { get; set; }
        public decimal GrossTurnOver { get; set; }
        public string StateCode { get; set; }
        public string GSTINUserId { get; set; }
        public string NameOfSignatory { get; set; }
        public string Designation { get; set; }
        public Nullable<bool> RegisterWithUs { get; set; }
        public Nullable<byte> UserType { get; set; }
        public Nullable<decimal> ITC { get; set; }
        public byte[] SmallImage { get; set; }
        public byte[] LargeImage { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual ICollection<AspNetUserAppData> AspNetUserAppDatas { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual ICollection<AspNetUserRole> AspNetUserRoles1 { get; set; }
        public virtual ICollection<GST_MST_USER_SIGNATORY> GST_MST_USER_SIGNATORY { get; set; }
        public virtual ICollection<GST_MST_ITEM> GST_MST_ITEM { get; set; }
        public virtual ICollection<GST_MST_PRESENT_USER> GST_MST_PRESENT_USER { get; set; }
        public virtual ICollection<GST_MST_PURCHASE_REGISTER> GST_MST_PURCHASE_REGISTER { get; set; }
        public virtual ICollection<GST_MST_REPORT_PERMISSION> GST_MST_REPORT_PERMISSION { get; set; }
        public virtual ICollection<GST_MST_SALE_REGISTER> GST_MST_SALE_REGISTER { get; set; }
        public virtual ICollection<GST_MST_USER_BUSINESSTYPE> GST_MST_USER_BUSINESSTYPE { get; set; }
        public virtual ICollection<GST_MST_USER_CURRENT_TURNOVER> GST_MST_USER_CURRENT_TURNOVER { get; set; }
        public virtual ICollection<GST_MST_VENDOR> GST_MST_VENDOR { get; set; }
        public virtual ICollection<GST_TRN_CRDR_NOTE> GST_TRN_CRDR_NOTE { get; set; }
        public virtual ICollection<GST_TRN_CRDR_NOTE> GST_TRN_CRDR_NOTE1 { get; set; }
        public virtual ICollection<GST_TRN_INVOICE> GST_TRN_INVOICE { get; set; }
        public virtual ICollection<GST_TRN_INVOICE> GST_TRN_INVOICE1 { get; set; }
        public virtual ICollection<GST_TRN_INVOICE> GST_TRN_INVOICE2 { get; set; }
        public virtual ICollection<GST_TRN_ITC> GST_TRN_ITC { get; set; }
        public virtual ICollection<GST_TRN_OFFLINE_INVOICE> GST_TRN_OFFLINE_INVOICE { get; set; }
        public virtual ICollection<GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL> GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL { get; set; }
        public virtual ICollection<GST_TRN_RETURN_STATUS> GST_TRN_RETURN_STATUS { get; set; }
    }
}
