//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWB_TRN_EWBILL_ITEM
    {
        public int Product_ID { get; set; }
        public Nullable<int> EWB_ID { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<int> HsnCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string QtyUnit { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> CGSTRate { get; set; }
        public Nullable<decimal> SGSTRate { get; set; }
        public Nullable<decimal> IGSTRate { get; set; }
        public Nullable<decimal> CESSRate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EWB_TRN_EWBILL EWB_TRN_EWBILL { get; set; }
    }
}
