//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWB_TRN_EWBILL
    {
        public EWB_TRN_EWBILL()
        {
            this.EWB_TRN_CANCEL_EWBILL = new HashSet<EWB_TRN_CANCEL_EWBILL>();
            this.EWB_TRN_CONSOLIDATED_EWBILL = new HashSet<EWB_TRN_CONSOLIDATED_EWBILL>();
            this.EWB_TRN_EWBILL_AUDITTRAIL = new HashSet<EWB_TRN_EWBILL_AUDITTRAIL>();
            this.EWB_TRN_EWBILL_ITEM = new HashSet<EWB_TRN_EWBILL_ITEM>();
            this.EWB_TRN_REJECT_EWBILL = new HashSet<EWB_TRN_REJECT_EWBILL>();
            this.EWB_TRN_REPONSE_EWBILL = new HashSet<EWB_TRN_REPONSE_EWBILL>();
            this.EWB_TRN_UPDATE_VEHICLE = new HashSet<EWB_TRN_UPDATE_VEHICLE>();
        }
    
        public int EWB_ID { get; set; }
        public string UserID { get; set; }
        public string UserGSTIN { get; set; }
        public Nullable<byte> SupplyType { get; set; }
        public Nullable<int> SubSupplyType { get; set; }
        public string DocType { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string FromGSTIN { get; set; }
        public Nullable<int> ActFromStateCode { get; set; }
        public string FromTrdName { get; set; }
        public string FromAddress1 { get; set; }
        public string FromAddress2 { get; set; }
        public string FromPlace { get; set; }
        public Nullable<int> FromPincode { get; set; }
        public Nullable<int> FromStateCode { get; set; }
        public string ToGSTIN { get; set; }
        public Nullable<int> ActToStateCode { get; set; }
        public string ToTrdName { get; set; }
        public string ToAddress1 { get; set; }
        public string ToAddress2 { get; set; }
        public string ToPlace { get; set; }
        public Nullable<int> ToPincode { get; set; }
        public Nullable<int> ToStateCode { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<decimal> CGSTValue { get; set; }
        public Nullable<decimal> SGSTValue { get; set; }
        public Nullable<decimal> IGSTValue { get; set; }
        public Nullable<decimal> CessValue { get; set; }
        public Nullable<int> TransMode { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> TransDistance { get; set; }
        public string TransporterId { get; set; }
        public string TransporterName { get; set; }
        public string TransDocNo { get; set; }
        public Nullable<System.DateTime> TransDocDate { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<byte> Status { get; set; }
        public string ErrorCodes { get; set; }
        public string EWBDocNo { get; set; }
        public Nullable<int> EwayBillNo { get; set; }
        public Nullable<System.DateTime> EwayBillDate { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EWB_MST_SUBSUPPLY_TYPE EWB_MST_SUBSUPPLY_TYPE { get; set; }
        public virtual ICollection<EWB_TRN_CANCEL_EWBILL> EWB_TRN_CANCEL_EWBILL { get; set; }
        public virtual ICollection<EWB_TRN_CONSOLIDATED_EWBILL> EWB_TRN_CONSOLIDATED_EWBILL { get; set; }
        public virtual ICollection<EWB_TRN_EWBILL_AUDITTRAIL> EWB_TRN_EWBILL_AUDITTRAIL { get; set; }
        public virtual ICollection<EWB_TRN_EWBILL_ITEM> EWB_TRN_EWBILL_ITEM { get; set; }
        public virtual ICollection<EWB_TRN_REJECT_EWBILL> EWB_TRN_REJECT_EWBILL { get; set; }
        public virtual ICollection<EWB_TRN_REPONSE_EWBILL> EWB_TRN_REPONSE_EWBILL { get; set; }
        public virtual ICollection<EWB_TRN_UPDATE_VEHICLE> EWB_TRN_UPDATE_VEHICLE { get; set; }
    }
}
