//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_TRN_INVOICE_AUDIT_TRAIL
    {
        public long AuditTrailID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<byte> AuditTrailStatus { get; set; }
        public string UserIP { get; set; }
        public Nullable<byte> InvoiceAction { get; set; }
        public Nullable<byte> SellerInvoiceAction { get; set; }
        public Nullable<byte> ReceiverInvoiceAction { get; set; }
        public Nullable<System.DateTime> SellerInvoiceActionDate { get; set; }
        public Nullable<System.DateTime> ReceiverInvoiceActionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual GST_TRN_INVOICE GST_TRN_INVOICE { get; set; }
    }
}
