//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_TRN_OFFLINE_INVOICE
    {
        public GST_TRN_OFFLINE_INVOICE()
        {
            this.GST_TRN_OFFLINE_INVOICE_DATAITEM = new HashSet<GST_TRN_OFFLINE_INVOICE_DATAITEM>();
        }
    
        public int ValueId { get; set; }
        public Nullable<long> OfflineID { get; set; }
        public string UserID { get; set; }
        public string SupplierGSTIN { get; set; }
        public string SupplierName { get; set; }
        public string ReceiverGSTIN { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string TotalInvoiceValue { get; set; }
        public Nullable<byte> PlaceofSupply { get; set; }
        public Nullable<byte> SupplyType { get; set; }
        public byte SectionType { get; set; }
        public byte ReturnType { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public Nullable<bool> ReverseCharge { get; set; }
        public string ECommerce_GSTIN { get; set; }
        public Nullable<byte> Type { get; set; }
        public string Voucher_No { get; set; }
        public Nullable<System.DateTime> Voucher_date { get; set; }
        public string Document_Type { get; set; }
        public Nullable<int> Issuing_Note { get; set; }
        public string Voucher_Value { get; set; }
        public Nullable<bool> Pre_GST { get; set; }
        public Nullable<byte> GST_Payment { get; set; }
        public string PortCode { get; set; }
        public string ShippingBillNo { get; set; }
        public Nullable<System.DateTime> ShippingBillDate { get; set; }
        public string HSN { get; set; }
        public Nullable<byte> UQC { get; set; }
        public string HSNDescription { get; set; }
        public Nullable<byte> NoteType { get; set; }
        public string BillOfEntry { get; set; }
        public Nullable<System.DateTime> BillofEntryDate { get; set; }
        public Nullable<decimal> BillofEntryValue { get; set; }
        public Nullable<bool> ImportfromSEZ { get; set; }
        public Nullable<bool> CompoundingDealerSupplies { get; set; }
        public Nullable<bool> NilRated { get; set; }
        public Nullable<bool> IsExempted { get; set; }
        public Nullable<bool> NonGSTSupplies { get; set; }
        public Nullable<byte> URType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GST_MST_STATE GST_MST_STATE { get; set; }
        public virtual GST_TRN_OFFLINE GST_TRN_OFFLINE { get; set; }
        public virtual ICollection<GST_TRN_OFFLINE_INVOICE_DATAITEM> GST_TRN_OFFLINE_INVOICE_DATAITEM { get; set; }
        public virtual GST_TRN_OFFLINE_ISSUINGNOTE_REASON GST_TRN_OFFLINE_ISSUINGNOTE_REASON { get; set; }
    }
}
