//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_BUSINESSTYPE
    {
        public GST_MST_BUSINESSTYPE()
        {
            this.GST_MST_ITEM = new HashSet<GST_MST_ITEM>();
            this.GST_MST_USER_BUSINESSTYPE = new HashSet<GST_MST_USER_BUSINESSTYPE>();
        }
    
        public int BusinessID { get; set; }
        public string BusinessType { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<GST_MST_ITEM> GST_MST_ITEM { get; set; }
        public virtual ICollection<GST_MST_USER_BUSINESSTYPE> GST_MST_USER_BUSINESSTYPE { get; set; }
    }
}
