//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_TRN_CONSOLIDATED_INVOICE
    {
        public long ReconsileID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> InvoiceDataID { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<byte> INVOICESPECIALCONDITION { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> TAXABLEAMOUNT { get; set; }
        public string GSTNNO { get; set; }
    
        public virtual GST_TRN_INVOICE GST_TRN_INVOICE { get; set; }
    }
}
