//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_VENDOR_TRANS_SHIPMENT
    {
        public GST_MST_VENDOR_TRANS_SHIPMENT()
        {
            this.GST_TRN_INVOICE = new HashSet<GST_TRN_INVOICE>();
        }
    
        public long TransShipment_ID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string TransShipmentNo { get; set; }
        public string VehicleRegistrationNumber { get; set; }
        public string DriverLicenceNumber { get; set; }
        public Nullable<bool> IsInterNationalWarehouseAvailed { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<System.DateTime> TransShipmentDate { get; set; }
        public Nullable<int> Distance_ID { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<byte> TransShipmentStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual GST_MST_ITEM GST_MST_ITEM { get; set; }
        public virtual GST_MST_VENDOR GST_MST_VENDOR { get; set; }
        public virtual ICollection<GST_TRN_INVOICE> GST_TRN_INVOICE { get; set; }
    }
}
