//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_VENDOR_SERVICE
    {
        public int VendorServiceID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> Item_ID { get; set; }
    
        public virtual GST_MST_ITEM GST_MST_ITEM { get; set; }
        public virtual GST_MST_VENDOR GST_MST_VENDOR { get; set; }
    }
}
