//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_SUBGROUP
    {
        public GST_MST_SUBGROUP()
        {
            this.GST_MST_CLASS = new HashSet<GST_MST_CLASS>();
            this.GST_MST_ITEM = new HashSet<GST_MST_ITEM>();
        }
    
        public int SubGroupID { get; set; }
        public string SubGroupCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<GST_MST_CLASS> GST_MST_CLASS { get; set; }
        public virtual GST_MST_GROUP GST_MST_GROUP { get; set; }
        public virtual ICollection<GST_MST_ITEM> GST_MST_ITEM { get; set; }
    }
}
