//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_STATE
    {
        public GST_MST_STATE()
        {
            this.GST_MST_VENDOR = new HashSet<GST_MST_VENDOR>();
            this.GST_TRN_OFFLINE_INVOICE = new HashSet<GST_TRN_OFFLINE_INVOICE>();
        }
    
        public byte StateID { get; set; }
        public string StateName { get; set; }
        public string StateCode { get; set; }
        public string StateCodeID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> CompCeilingAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> UT { get; set; }
        public Nullable<bool> IsExempted { get; set; }
    
        public virtual ICollection<GST_MST_VENDOR> GST_MST_VENDOR { get; set; }
        public virtual ICollection<GST_TRN_OFFLINE_INVOICE> GST_TRN_OFFLINE_INVOICE { get; set; }
    }
}
