//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_PRODUCT_DESCRIPTION
    {
        public int ProductID { get; set; }
        public string MarksNos { get; set; }
        public string Packages { get; set; }
        public string GoodDescription { get; set; }
        public decimal Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
    }
}
