//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWB_TRN_CONSOLIDATED_EWBILL
    {
        public int ConsolidatedID { get; set; }
        public Nullable<int> EWB_ID { get; set; }
        public string VehicleNo { get; set; }
        public string FromPlace { get; set; }
        public Nullable<int> TransMode { get; set; }
        public string TransDocNo { get; set; }
        public Nullable<System.DateTime> TransDocDate { get; set; }
        public Nullable<int> FromState { get; set; }
        public string TripSheetEWBBills { get; set; }
        public Nullable<int> EWBNo { get; set; }
        public Nullable<byte> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EWB_TRN_EWBILL EWB_TRN_EWBILL { get; set; }
    }
}
