//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_EXCEPTIONLOG
    {
        public long EXCEPTIONID { get; set; }
        public string USERNAME { get; set; }
        public string APPLICATIONNAME { get; set; }
        public string EXCEPTIONCLASSNAME { get; set; }
        public string EXCEPTIONMETHODNAME { get; set; }
        public string EXCEPTIONMESSAGE { get; set; }
        public string EXCEPTIONLINENUMBER { get; set; }
        public string SERVERNAME { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> EXCEPTIONLOGGINGTIME { get; set; }
    }
}
