//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_TRN_INVOICE
    {
        public GST_TRN_INVOICE()
        {
            this.EWB_TRN_REPONSE_EWBILL = new HashSet<EWB_TRN_REPONSE_EWBILL>();
            this.GST_MST_SALE_REGISTER = new HashSet<GST_MST_SALE_REGISTER>();
            this.GST_MST_USER_CURRENT_TURNOVER = new HashSet<GST_MST_USER_CURRENT_TURNOVER>();
            this.GST_TRN_CONSOLIDATED_INVOICE = new HashSet<GST_TRN_CONSOLIDATED_INVOICE>();
            this.GST_TRN_CRDR_NOTE = new HashSet<GST_TRN_CRDR_NOTE>();
            this.GST_TRN_INVOICE_AUDIT_TRAIL = new HashSet<GST_TRN_INVOICE_AUDIT_TRAIL>();
            this.GST_TRN_INVOICE_DATA = new HashSet<GST_TRN_INVOICE_DATA>();
            this.GST_TRN_ITC = new HashSet<GST_TRN_ITC>();
        }
    
        public long InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceUserID { get; set; }
        public Nullable<byte> InvoiceMonth { get; set; }
        public string SellerUserID { get; set; }
        public string ReceiverUserID { get; set; }
        public string ConsigneeUserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<long> TransShipment_ID { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> PackingAndForwadingCharges { get; set; }
        public string ElectronicReferenceNo { get; set; }
        public Nullable<System.DateTime> ElectronicReferenceNoDate { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public Nullable<int> FinYear_ID { get; set; }
        public Nullable<byte> InvoiceMode { get; set; }
        public Nullable<bool> IsInter { get; set; }
        public Nullable<int> ReceiverFinYear_ID { get; set; }
        public Nullable<long> ParentInvoiceID { get; set; }
        public Nullable<byte> InvoiceStatus { get; set; }
        public string TaxBenefitingState { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<byte> InvoiceSpecialCondition { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<EWB_TRN_REPONSE_EWBILL> EWB_TRN_REPONSE_EWBILL { get; set; }
        public virtual GST_MST_FINYEAR GST_MST_FINYEAR { get; set; }
        public virtual ICollection<GST_MST_SALE_REGISTER> GST_MST_SALE_REGISTER { get; set; }
        public virtual ICollection<GST_MST_USER_CURRENT_TURNOVER> GST_MST_USER_CURRENT_TURNOVER { get; set; }
        public virtual GST_MST_VENDOR GST_MST_VENDOR { get; set; }
        public virtual GST_MST_VENDOR_TRANS_SHIPMENT GST_MST_VENDOR_TRANS_SHIPMENT { get; set; }
        public virtual ICollection<GST_TRN_CONSOLIDATED_INVOICE> GST_TRN_CONSOLIDATED_INVOICE { get; set; }
        public virtual ICollection<GST_TRN_CRDR_NOTE> GST_TRN_CRDR_NOTE { get; set; }
        public virtual ICollection<GST_TRN_INVOICE_AUDIT_TRAIL> GST_TRN_INVOICE_AUDIT_TRAIL { get; set; }
        public virtual ICollection<GST_TRN_INVOICE_DATA> GST_TRN_INVOICE_DATA { get; set; }
        public virtual ICollection<GST_TRN_ITC> GST_TRN_ITC { get; set; }
    }
}
