//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_MST_SALEREGISTER
    {
        public long RegisterID { get; set; }
        public string UserID { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> HSN_Id { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<long> PerUnitRate { get; set; }
        public Nullable<System.DateTime> StockInwardDate { get; set; }
        public Nullable<System.DateTime> StackOrderDate { get; set; }
        public string OrderPo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
