//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GST_TRN_OFFLINE
    {
        public GST_TRN_OFFLINE()
        {
            this.GST_TRN_OFFLINE_INVOICE = new HashSet<GST_TRN_OFFLINE_INVOICE>();
        }
    
        public long OfflineID { get; set; }
        public Nullable<long> AuditTrailID { get; set; }
        public Nullable<byte> FileType { get; set; }
        public string UploadedBy { get; set; }
        public string SupplierGSTIN { get; set; }
        public Nullable<int> Fin_ID { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<decimal> AggregateTurnover { get; set; }
        public Nullable<decimal> AggregateTurnoverQuater { get; set; }
        public Nullable<byte> Section { get; set; }
        public string ExcelData { get; set; }
        public Nullable<byte> UploadStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL GST_TRN_OFFLINE_INVOICE_AUDIT_TRAIL { get; set; }
        public virtual ICollection<GST_TRN_OFFLINE_INVOICE> GST_TRN_OFFLINE_INVOICE { get; set; }
    }
}
