//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTR3B_2_2
    {
        public string Description { get; set; }
        public Nullable<decimal> TAXABLEAMOUNT { get; set; }
        public Nullable<decimal> IGSTAMT { get; set; }
        public string STATENAME { get; set; }
    }
}
