//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALAJI.GSP.APPLICATION.User.ureturn {
    
    
    public partial class GSTR1APreviewB2B {
        
        /// <summary>
        /// uc_GSTR_Taxpayer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BALAJI.GSP.APPLICATION.UC.uc_GSTR_Taxpayer uc_GSTR_Taxpayer;
        
        /// <summary>
        /// uc_Signatory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BALAJI.GSP.APPLICATION.UC.uc_Signatory uc_Signatory;
        
        /// <summary>
        /// lkvGSTR1A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lkvGSTR1A;
        
        /// <summary>
        /// lv_GSTR1A_3A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR1A_3A;
        
        /// <summary>
        /// lv_GSTR1A_3B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR1A_3B;
        
        /// <summary>
        /// lv_GSTR_1A_4A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR_1A_4A;
        
        /// <summary>
        /// lv_GSTR_1A_4B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR_1A_4B;
        
        /// <summary>
        /// lv_GSTR_1A_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR_1A_5;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BALAJI.GSP.APPLICATION.User.User Master {
            get {
                return ((BALAJI.GSP.APPLICATION.User.User)(base.Master));
            }
        }
    }
}
