//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALAJI.GSP.APPLICATION.User.ureturn {
    
    
    public partial class GSTR2APreviewB2B {
        
        /// <summary>
        /// uc_GSTR_Taxpayer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BALAJI.GSP.APPLICATION.UC.uc_GSTR_Taxpayer uc_GSTR_Taxpayer;
        
        /// <summary>
        /// lv_GSTR2A_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_3;
        
        /// <summary>
        /// lv_GSTR2A_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_4;
        
        /// <summary>
        /// lv_GSTR2A_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_5;
        
        /// <summary>
        /// lv_GSTR2A_6_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_6_1;
        
        /// <summary>
        /// lv_GSTR2A_6_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_6_2;
        
        /// <summary>
        /// lv_GSTR2A_6_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_6_3;
        
        /// <summary>
        /// lv_GSTR2A_6_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_6_4;
        
        /// <summary>
        /// lv_GSTR2A_7A control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_7A;
        
        /// <summary>
        /// lv_GSTR2A_7B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lv_GSTR2A_7B;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BALAJI.GSP.APPLICATION.User.User Master {
            get {
                return ((BALAJI.GSP.APPLICATION.User.User)(base.Master));
            }
        }
    }
}
