//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALAJI.GSP.APPLICATION.User.ureturn {
    
    
    public partial class ReturnGstr1 {
        
        /// <summary>
        /// ddlfinYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlfinYear;
        
        /// <summary>
        /// uc_invoiceMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BALAJI.GSP.APPLICATION.UC.UC_Invoice.uc_invoiceMonth uc_invoiceMonth;
        
        /// <summary>
        /// btnSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        /// <summary>
        /// uc_Gstr_Tileview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BALAJI.GSP.APPLICATION.UC.UC_Gstr.uc_Gstr_Tileview uc_Gstr_Tileview;
    }
}
